### ISSUE TITLE
Can't delete NGOs in the CMS

### ISSUE THREAD

**Issue by WeFeelTheWorld** [magnolo/newhere#124]
Station Wien hat eigenen Account erstellt.

Konnten im CMS unseren Account in Station Wien**\* umbenennen. Allerdings kann ich jetzt nimmer löschen..

**Comment by hiasel** [comment]
kann den Bug grad nicht nachvollziehen. 
Hab gerade die letzte Version lokal laufen lassen und kann alle NGOs problemlos löschen (Auch mit Angeboten oder User). 
Auf der Live-Website hab ichs nicht getestet (will ja euch ja keine NGOs weglöschen ;) ).

Wurde das schon gefixt?
