### ISSUE TITLE
Phone Number regex

### ISSUE THREAD

**Issue by hiasel** [magnolo/newhere#127]
Some NGOs have stored phone number in following format: 0043xxxxxxxx
our regex pattern currently only allows +43xxxxxxxxx
(regex: /^((+\d{1,3}(-| )?(?\d)?(-| )?\d{1,5})|((?\d{2,6})?))(-| )?(\d{3,4})(-| )?(\d{4})(( x| ext)\d{1,5}){0,1}$/)

Example: In CMS if you want to edit a NGO and the number is stored in 0043 the form is invalid.

**Comment by mmiheller** [comment]
fixed
