### ISSUE TITLE
Im CMS: Offer Liste: NGO Suche funzt nicht

### ISSUE THREAD

**Issue by WeFeelTheWorld** [magnolo/newhere#130]
Station wien wird in der Liste angezeigt. Wenn ich es allerdings suche, dann wird mir nüscht angezeigt.

**Comment by hiasel** [comment]
grade auf der Website ausprobiert, kanns nicht nachvollziehen.
"Station Wien" in der Suche zeigts unten in der Liste an?!
![bildschirmfoto 2016-06-27 um 19 02 42](https://cloud.githubusercontent.com/assets/5979479/16388533/cfbc385a-3c99-11e6-9069-9f4928595e22.png)
