### ISSUE TITLE
im CMS: NGO Liste: Sortieren nach veröffentlicht

### ISSUE THREAD

**Issue by WeFeelTheWorld** [magnolo/newhere#132]
sonst kann man schwer die neuen NGOs finden. Kann man hier einen Listenfilter(Sortiere einbauen bitte?

![bildschirmfoto 2016-06-27 um 18 29 11](https://cloud.githubusercontent.com/assets/20107924/16387440/2110471e-3c95-11e6-99ff-b0ff2edf3e22.png)

**Comment by hiasel** [comment]
das sollte schon funktionieren, oben neben der Suche über das "Veröffentlicht" - Dropdown.
![bildschirmfoto 2016-06-27 um 18 59 04](https://cloud.githubusercontent.com/assets/5979479/16388423/672cee4c-3c99-11e6-833b-8e656f9bfa03.png)
