### ISSUE TITLE
Cannot edit offers / phone number format

### ISSUE THREAD

**Issue by WeFeelTheWorld** [magnolo/newhere#133]
Can only edit an entry when the telephone number starts with a '+' but there is no error message. Should take any format or make clear what format is needed (see last photo). Are there any other barriers to pressing the save button which are not made clear e.g. accompanied by an error message?

![bildschirmfoto 2016-09-23 um 19 07 30](https://cloud.githubusercontent.com/assets/20107924/18794750/58f5fdec-81c1-11e6-8993-5430170375f4.png)

![bildschirmfoto 2016-09-23 um 19 07 54](https://cloud.githubusercontent.com/assets/20107924/18794752/5be6b6ae-81c1-11e6-8c9f-064e7f91f946.png)

![bildschirmfoto 2016-09-23 um 19 11 30](https://cloud.githubusercontent.com/assets/20107924/18794812/9d13e228-81c1-11e6-98a6-a6a4f28d2522.png)

Chrome Version 54.0.2840.59 beta (64-bit)/ OS X El Capitan Version 10.11.6

**Comment by kmay90** [comment]
A similar problem exists when trying to create an NGO account. The fields marked with '*' are not actually the only obligatory fields (although they should be) and telephone  number and website have to be included in a very specific, but unspecified, format e.g. not google.com but https://www.google.at/?gfe_rd=cr&ei=2owQWJLUHaOh8welvY2IAQ&gws_rd=ssl and not +436604123456 but 00436604123456.

When something is entered wrong, no error message shows.

Ideally only the fields marked\* would actually be obligatory and any special formatting requirements would be clearly stated.

[Can't add screenshots now but will add them asap]

**Comment by kmay90** [comment]
Fantastic - the only problem now is that the 'website' field still needs a special format (directly copied URL) to be accepted but doesn't show any error message when this is not done. The website field could read (in grey, before they click in the field) 'please copy and paste your URL here', to make it clearer:
![screen shot 2016-11-14 at 22 01 21](https://cloud.githubusercontent.com/assets/22774962/20282697/2798fcb8-aab6-11e6-9d74-742130253d62.png)

**Comment by magnolo** [comment]
yeah the input type for url requires the protocol like http:// or https:// in front of the url.. i added a hint for that

**Comment by kmay90** [comment]
Could we please change the text to 'Please copy and paste your URL here'
