### ISSUE TITLE
Map view not coherent with offers

### ISSUE THREAD

**Issue by kmay90** [magnolo/newhere#142]
The points shown on the map are not coherent with the offers being viewed e.g. Categorisation not coherent with map view e.g. one schule = 100s of points on the map:

![screen shot 2016-10-23 at 19 02 04](https://cloud.githubusercontent.com/assets/22774962/19627957/6a0b3666-9953-11e6-99a5-e2fef5ba163d.png)

Chrome Version 54.0.2840.59 beta (64-bit)/ OS X El Capitan Version 10.11.6

**Comment by magnolo** [comment]
this bug appeared when u go to fast threw the categories and the previous response from the server wasnt finished
