### ISSUE TITLE
'Rights' of the different account types

### ISSUE THREAD

**Issue by kmay90** [magnolo/newhere#156]
1) [QUESTION] What are the 'rights' attributed to the different account types e.g. super admin, moderator, admin, organisation admin, organisation user, user?

2) [BUG] Ideally, we would be able to attribute 'moderator' to our translators and they would be able to see ONLY their account and the translation tab, which they would have full access to. This is not currently the case. At the moment, when a user is made a 'moderator' they can only see their account and offers (despite having none) as if they were a normal NGO.

**Comment by magnolo** [comment]
All menus and contents are now adjusted to for the selected user rights... moderator is allowed to see translations. Superadmin is allowed to ajust user accounts what an admin cant..
