### ISSUE TITLE
New users cannot login after verification

### ISSUE THREAD

**Issue by trizadolez** [magnolo/newhere#157]
An NGO makes a new user account, we verify it (switch on in CMS), but then they can't login. 

When they try to login, the following error message shows: "Your account has not been verified. Did you get mail?"

![picture device independent bitmap 1](https://cloud.githubusercontent.com/assets/22840489/21008126/a1699600-bd40-11e6-8366-6ee63ecf0094.jpg)

Ideally no error message would show and they would be able to log in as normal.

We can all login as normal with our accounts, but any new account holders not.

Our translators can also login and their accounts were made relatively recently - therefore, maybe this has something to do with the different rights allocation e.g. user, admin, etc.

Safari + 10.12.1 Mac OS

**Comment by magnolo** [comment]
For activation from an admin out of the cms this works as expected but the confirmation email from the registration process didnt reach my inbox... on my local machine everything seems perfect. Maybe this has something to do with the mail server configuration of the app... I am on it
