### ISSUE TITLE
Translator tool lag

### ISSUE THREAD

**Issue by kmay90** [magnolo/newhere#182]
The lag on the translation tool is making it impossible for the translators to work and is top priority to be fixed

**Comment by ScrambledRK** [comment]
I suspect you mean /cms/translations and the initial loading time? or is there something else called translator tool? In case it is /cms/translations it seems that the "untranslated" query takes very long to respond, meaning the backend is probably taking a long time to come up with a response.

> /api/offer-translations/untranslated
> /api/category-translations/untranslated
> /api/filter-translations/untranslated
> /api/ngo-translations/untranslated

in addition that a single query already takes a long time, all 4 are called regardless of the translations you are interested in (offers/category/filter/ngo).
