### ISSUE TITLE
Deactivated offers are still visible

### ISSUE THREAD

**Issue by kmay90** [magnolo/newhere#189]
The list below shows all Angebote which have been deactivated:

![screen shot 2017-05-22 at 12 54 07](https://cloud.githubusercontent.com/assets/22774962/26305015/dc17a74a-3eed-11e7-8624-d1df17382f95.png)

However, they are still shown on the map: (I think this is an old test account, for example)

![screen shot 2017-05-22 at 12 55 39](https://cloud.githubusercontent.com/assets/22774962/26305040/fdef1c4a-3eed-11e7-8f86-a74a7dacb75a.png)

Ideally, both NGOs and admins would be able to 'hide' or 'unhide' Angebote easily. For example, in the case that a course is full or closes over summer.

**Comment by ScrambledRK** [comment]
unsure about priority. are end-user (people consuming content) or cms-user (people providing content) in focus for the next few rounds of bug fixing?
