### ISSUE TITLE
Users -> double + top right

### ISSUE THREAD

**Issue by ras-martin** [magnolo/newhere#30]
The double + top right in screen is a little bit confusing.
The first + links to the role list?!

**Comment by hiasel** [comment]
![bildschirmfoto 2016-05-18 um 11 50 25](https://cloud.githubusercontent.com/assets/5979479/15354629/d39b07c8-1cee-11e6-82e8-a35bbc22fcb1.png)

**Comment by magnolo** [comment]
changed the icon to differ from each other. first link goes to list the roles.
