### ISSUE TITLE
Users/Add User --> Switch has no meaning(?!)

### ISSUE THREAD

**Issue by hiasel** [magnolo/newhere#45]
When creating a new User in the CMS, a pop-up to create the user shows up.
On top of the pop-up there is a switch that has no label and no function(?!)
![bildschirmfoto 2016-05-18 um 11 52 30](https://cloud.githubusercontent.com/assets/5979479/15354718/3de5e756-1cef-11e6-8432-e24c6d0e98eb.png)

**Comment by magnolo** [comment]
This switch enables/disables the user account

**Comment by hiasel** [comment]
makes sense then ;)
