### ISSUE TITLE
Map: Icon for fullscreen is missing

### ISSUE THREAD

**Issue by connyduck** [magnolo/newhere#97]
see screenshot 
<img width="145" alt="screen shot 2016-06-18 at 18 20 50" src="https://cloud.githubusercontent.com/assets/10157047/16172123/76e88108-3581-11e6-90d7-f3eabff81dbc.png">

**Comment by magnolo** [comment]
there was just an image missing that is linked in the css file from leaflet-fullscreen-plugin.
